{
    'name': 'intranet_MTND',
    'version': '1.0',
    'category': 'Gestion/Patrimoine',
    'summary': 'Module de gestion des biens matériels (véhicules, informatique, mobilier)',
    'author': 'Coulibaly Yadjiman',
    'website': 'http://www.example.com',
    'depends': ['base', 'hr', 'stock', 'account', 'fleet', 'bus'],
    "data": [
        "data/sequence.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "views/asset_informatique_views.xml",
        "views/asset_mobilier_views.xml",
        "views/asset_vehicule_views.xml",
        "views/asset_views.xml",
        "views/entretien_views.xml",
        "views/fiche_vie_views.xml",
        "views/menu.xml",
        "views/mouvement_views.xml",
        "views/perte_views.xml",
        "views/demande_materiel_views.xml",
        "views/asset_category_views.xml",
        "views/asset_custom_field_views.xml",
        "views/asset_subcategory_views.xml",
        "reports/report_patrimoine_templates.xml",
        "reports/report_patrimoine.xml",
    ],
    'controllers': [
        'controllers/userApi_controller.py',
        'controllers/asset_controller.py',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
